services:
  redis-staging-cluster-node1:
    image: bitnami/redis-cluster:7.2.5
    container_name: redis-staging-cluster-node1
    ports:
      - 6376:6376
      - 16376:16376
    environment:
      REDIS_CLUSTER_DYNAMIC_IPS: no
      REDIS_CLUSTER_ANNOUNCE_IP: 192.168.29.94
      REDIS_PORT_NUMBER: 6376
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: 192.168.29.94:6376 192.168.29.94:6377 192.168.29.94:6378 192.168.29.94:6380
  redis-staging-cluster-node2:
    image: bitnami/redis-cluster:7.2.5
    container_name: redis-staging-cluster-node2
    ports:
      - 6377:6377
      - 16377:16377
    environment:
      REDIS_CLUSTER_DYNAMIC_IPS: no
      REDIS_CLUSTER_ANNOUNCE_IP: 192.168.29.94
      REDIS_PORT_NUMBER: 6377
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: 192.168.29.94:6377 192.168.29.94:6377 192.168.29.94:6378 192.168.29.94:6380
  redis-staging-cluster-node3:
    image: bitnami/redis-cluster:7.2.5
    container_name: redis-staging-cluster-node3
    ports:
      - 6378:6378
      - 16378:16378
    environment:
      REDIS_CLUSTER_DYNAMIC_IPS: no
      REDIS_CLUSTER_ANNOUNCE_IP: 192.168.29.94
      REDIS_PORT_NUMBER: 6378
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: 192.168.29.94:6377 192.168.29.94:6377 192.168.29.94:6378 192.168.29.94:6380
  redis-staging-cluster-node4:
    image: bitnami/redis-cluster:7.2.5
    container_name: redis-staging-cluster-node4
    ports:
      - 6380:6380
      - 16380:16380
    environment:
      REDIS_CLUSTER_DYNAMIC_IPS: no
      REDIS_CLUSTER_ANNOUNCE_IP: 192.168.29.94
      REDIS_PORT_NUMBER: 6380
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: 192.168.29.94:6377 192.168.29.94:6377 192.168.29.94:6378 192.168.29.94:6380
      REDIS_CLUSTER_REPLICAS: 0
      REDIS_CLUSTER_CREATOR: yes
